### ISSUE TITLE
Application closes when trying to open a repo

### ISSUE THREAD

**Issue by DavidOcacho** [Noxdew/git-locks-manager#145] opened 2023-04-07 15:12 UTC
Please provide the following information:

**Operating system**:  Windows 11
**Version of the template**: I'm using 1.0.5

Please have a MVP (minimal viable product/example) that can reproduce the bug consistently. If you do not have a MVP, the issue will not get as much attention to fixing.

Thank you for taking the time to help make this project better.

Hey man! Trying to use your incredible tool but we are facing some problems when trying to add a repo
This is the output from the terminal:
![image](https://user-images.githubusercontent.com/126606809/230632634-c94dd5c5-5576-40e9-9ed6-44be1bab8aa5.png)

Steps:
Just try to add a repo

**Comment by morwoen** [comment] 2023-04-07 16:01
Hey, thanks for reporting.

The output doesn't seem to include any errors at all and I am not able to reproduce it. Does the application close without any signal at all? Do you see any error messages popping up just before it closes at the bottom of the window? What can you tell me about the repo, is it very large, do you have a lot of files locked currently?

I hope with these questions we can narrow down the root cause 🤞 🙂

**Comment by DavidOcacho** [comment] 2023-04-08 20:04
Hey man! 
Yes, without any signal at all. I don't see any error at the bottom of the window. I can tell you nothing about the repo cause I'm not able to open any repo. Hard bug tbh, sorry!
This is the last thing I see before the apps closes automatically 
![image](https://user-images.githubusercontent.com/126606809/230740501-1704e55c-3464-45d3-b969-a8a653cfe4e8.png)

BTW, a friend of mine could use the app without any error on W11, not sure what is going on. Thanks man!

**Comment by morwoen** [comment] 2023-04-18 13:20
Hey @DavidOcacho,
Apologies for the delayed response.
Am I understanding correctly that you tried it with multiple different repositories and it doesn't work with any of them?
Also is your friend able to open exactly the same repositories that you have failed to open on your machine?

This is indeed a very tricky one to debug :(

**Comment by morwoen** [comment] 2024-01-13 11:51
Hey, I'm going to close this issue. If you managed to solve your problem I'd be keen to know what the root cause was or how you did it. Feel free to still message in here with more info if help is still required and I will reopen it :)

**Closed by morwoen** 2024-01-13 11:51 UTC
